/* ═══════════════════════════════════════════════════════════════════
   PMS Kapal - Vercel Serverless Handler
   Auto-generated by build-vercel.js
   ═══════════════════════════════════════════════════════════════════ */

// Import hanya built-in Node.js modules
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// ── In-memory data store (ephemeral per cold start) ────────────────
let db = null;
const sessions = new Map();

const SEED_DATA = {
  roles: [
    { id: 'super-admin', name: 'Super Admin' },
    { id: 'fleet-manager', name: 'Fleet Manager' },
    { id: 'admin-kapal', name: 'Admin Kapal' },
    { id: 'teknisi', name: 'Teknisi' },
    { id: 'crew', name: 'Crew' },
    { id: 'hr', name: 'HR' },
    { id: 'finance', name: 'Finance' }
  ],
  users: [
    { id: 'u1', username: 'superadmin', password: 'pms-demo', name: 'Super Admin', roleId: 'super-admin', shipId: null },
    { id: 'u2', username: 'fleet', password: 'pms-demo', name: 'Fleet Manager', roleId: 'fleet-manager', shipId: null },
    { id: 'u3', username: 'nakhoda', password: 'pms-demo', name: 'Nakhoda', roleId: 'admin-kapal', shipId: 'ship-1' },
    { id: 'u4', username: 'teknisi', password: 'pms-demo', name: 'Teknisi', roleId: 'teknisi', shipId: 'ship-1' }
  ],
  ships: [
    { id: 'ship-1', name: 'KM Nusantara 01', imo: 'IMO-9012345', type: 'Cargo', flag: 'Indonesia', size: '3500 GT', photo: '' },
    { id: 'ship-2', name: 'KM Nusantara 02', imo: 'IMO-9076543', type: 'Tanker', flag: 'Indonesia', size: '5000 GT', photo: '' }
  ],
  equipments: [
    { id: 'eq-1', shipId: 'ship-1', name: 'Main Engine', category: 'Mesin', parentId: null, runningHours: 12500 },
    { id: 'eq-2', shipId: 'ship-1', name: 'Genset 1', category: 'Genset', parentId: null, runningHours: 8300 }
  ],
  schedules: [
    { id: 'sch-1', equipmentId: 'eq-1', title: 'Overhaul', basis: 'hours', intervalHours: 2000, nextDueAt: new Date(Date.now() + 5 * 86400000).toISOString(), status: 'due-soon' },
    { id: 'sch-2', equipmentId: 'eq-2', title: 'Ganti oli', basis: 'calendar', intervalDays: 90, nextDueAt: new Date(Date.now() - 10 * 86400000).toISOString(), status: 'overdue' }
  ],
  workOrders: [
    { id: 'wo-1', shipId: 'ship-1', title: 'Ganti oli Genset 1', assignee: 'Chief Engineer', status: 'open', createdAt: new Date().toISOString() }
  ],
  spareparts: [
    { id: 'sp-1', shipId: 'ship-1', code: 'SP-ME-001', name: 'Fuel Injector', stock: 4, minStock: 6 },
    { id: 'sp-2', shipId: 'ship-1', code: 'SP-GE-010', name: 'Oil Filter', stock: 20, minStock: 10 }
  ],
  sparepartUsages: [],
  costs: [
    { id: 'c-1', shipId: 'ship-1', kind: 'sparepart', amount: 3500000, date: new Date().toISOString(), note: 'Oil filter' },
    { id: 'c-2', shipId: 'ship-1', kind: 'jasa', amount: 5000000, date: new Date().toISOString(), note: 'Jasa teknisi' }
  ],
  budgets: [{ id: 'b-1', shipId: 'ship-1', period: '2026', amount: 500000000 }],
  crews: [
    { id: 'cr-1', shipId: 'ship-1', name: 'Ahmad Prasetyo', rank: 'Nakhoda', phone: '6281110001', status: 'onboard', photo: '', contracts: [] },
    { id: 'cr-2', shipId: 'ship-1', name: 'Budi Santoso', rank: 'KKM', phone: '6281110002', status: 'onboard', photo: '', contracts: [] }
  ],
  crewCertificates: [
    { id: 'cc-1', crewId: 'cr-1', type: 'COC Nautika', issuedAt: new Date(Date.now() - 700 * 86400000).toISOString(), expiredAt: new Date(Date.now() + 20 * 86400000).toISOString() },
    { id: 'cc-2', crewId: 'cr-2', type: 'Medical', issuedAt: new Date(Date.now() - 300 * 86400000).toISOString(), expiredAt: new Date(Date.now() - 2 * 86400000).toISOString() }
  ],
  attendances: [],
  leaves: [{ id: 'lv-1', crewId: 'cr-2', startDate: new Date(Date.now() + 30 * 86400000).toISOString(), endDate: new Date(Date.now() + 44 * 86400000).toISOString(), status: 'pending', reason: 'Cuti tahunan' }],
  activities: [{ id: 'act-1', shipId: 'ship-1', type: 'drill', title: 'Fire drill', date: new Date(Date.now() - 7 * 86400000).toISOString() }],
  shipDocuments: [
    { id: 'doc-1', shipId: 'ship-1', type: 'SMC', issuedAt: new Date(Date.now() - 800 * 86400000).toISOString(), expiredAt: new Date(Date.now() + 55 * 86400000).toISOString() },
    { id: 'doc-2', shipId: 'ship-1', type: 'Class Certificate', issuedAt: new Date(Date.now() - 900 * 86400000).toISOString(), expiredAt: new Date(Date.now() + 6 * 86400000).toISOString() }
  ],
  notificationConfigs: [
    { id: 'nc-1', targetType: 'crew-certificate', thresholds: [90, 60, 30, 14, 7, 1] },
    { id: 'nc-2', targetType: 'ship-document', thresholds: [90, 60, 30, 14, 7, 1] },
    { id: 'nc-3', targetType: 'maintenance', thresholds: [14, 7, 1] }
  ],
  notificationLogs: [],
  auditLogs: [],
  attachments: [],
  provider: { wa: 'mock', push: 'mock' },
  workOrderChecks: [],
  workOrderApprovals: []
};

function loadDb() {
  if (db) return db;
  db = JSON.parse(JSON.stringify(SEED_DATA));
  return db;
}

function send(res, code, data) {
  res.status(code).json(data);
}

function expiryStatus(expiredAt) {
  const diff = Math.ceil((new Date(expiredAt) - new Date()) / 86400000);
  if (diff < 0) return { status: 'expired', sisaHari: diff };
  if (diff <= 30) return { status: 'mendekati-expired', sisaHari: diff };
  return { status: 'aktif', sisaHari: diff };
}

function auth(req) {
  const t = (req.headers.authorization || '').replace('Bearer ', '');
  const id = sessions.get(t);
  return id ? db.users.find(u => u.id === id) : null;
}

function canWrite(user, key) {
  if (!user) return false;
  if (user.roleId === 'super-admin') return true;
  const perms = {
    'fleet-manager': ['ships', 'equipments', 'schedules', 'workOrders', 'spareparts', 'costs', 'budgets'],
    'admin-kapal': ['equipments', 'schedules', 'workOrders', 'spareparts', 'costs', 'crews', 'crewCertificates', 'leaves', 'activities', 'shipDocuments'],
    'teknisi': ['workOrders', 'schedules', 'spareparts'],
    'crew': ['leaves'],
    'hr': ['crews', 'crewCertificates', 'leaves', 'activities'],
    'finance': ['costs', 'budgets']
  };
  return (perms[user.roleId] || []).includes(key);
}

// ══════════════════════════════════════════════════════════════════
// Main Serverless Handler untuk Vercel
// ══════════════════════════════════════════════════════════════════
export default async function handler(req, res) {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', '*');
  res.setHeader('Access-Control-Allow-Methods', '*');
  
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  db = loadDb();
  const url = new URL(req.url, `http://${req.headers.host}`);
  const seg = url.pathname.split('/').filter(Boolean);
  const q = url.searchParams;

  // ── Public endpoints ────────────────────────────────────────────
  if (seg[seg.length - 1] === 'health') {
    return send(res, 200, { ok: true, platform: 'vercel', time: new Date().toISOString() });
  }

  if (seg[seg.length - 1] === 'login') {
    const u = db.users.find(x => x.username === req.body?.username && x.password === req.body?.password);
    if (!u) return send(res, 401, { error: 'Username/password salah' });
    const token = crypto.randomBytes(16).toString('hex');
    sessions.set(token, u.id);
    return send(res, 200, { token, user: { id: u.id, username: u.username, name: u.name, roleId: u.roleId, shipId: u.shipId } });
  }

  // ── Protected endpoints (butuh auth) ────────────────────────────
  const user = auth(req);
  if (!user) return send(res, 401, { error: 'Unauthorized' });

  // Dashboard fleet
  if (seg.includes('dashboard') && seg.includes('fleet')) {
    const ships = db.ships.map(s => {
      const docs = db.shipDocuments.filter(d => d.shipId === s.id).map(d => ({ ...d, ...expiryStatus(d.expiredAt) }));
      const certs = db.crewCertificates.filter(c => db.crews.find(x => x.id === c.crewId)?.shipId === s.id).map(c => ({ ...c, ...expiryStatus(c.expiredAt) }));
      const overdue = db.schedules.filter(x => db.equipments.find(e => e.id === x.equipmentId)?.shipId === s.id && x.status === 'overdue').length;
      const low = db.spareparts.filter(p => p.shipId === s.id && p.stock <= p.minStock).length;
      const urgency = docs.filter(d => d.status !== 'aktif').length + certs.filter(c => c.status !== 'aktif').length + overdue + low;
      return { ...s, expiredDocs: docs.filter(d => d.status !== 'aktif').length, expiredCerts: certs.filter(c => c.status !== 'aktif').length, overdue, lowStock: low, urgency };
    }).sort((a, b) => b.urgency - a.urgency);
    return send(res, 200, { ships });
  }

  // Dashboard ship
  if (seg.includes('dashboard') && seg.includes('ship')) {
    const id = seg[seg.indexOf('ship') + 1] || user.shipId || 'ship-1';
    const docs = db.shipDocuments.filter(d => d.shipId === id).map(d => ({ ...d, ...expiryStatus(d.expiredAt) }));
    const crews = db.crews.filter(c => c.shipId === id).map(c => ({ ...c, certificates: db.crewCertificates.filter(x => x.crewId === c.id).map(x => ({ ...x, ...expiryStatus(x.expiredAt) })) }));
    const eqs = db.equipments.filter(e => e.shipId === id).map(e => ({ ...e, schedules: db.schedules.filter(s => s.equipmentId === e.id) }));
    const costs = db.costs.filter(c => c.shipId === id);
    const total = costs.reduce((a, c) => a + Number(c.amount || 0), 0);
    return send(res, 200, {
      ship: db.ships.find(s => s.id === id),
      documents: docs,
      crews,
      equipments: eqs,
      spareparts: db.spareparts.filter(p => p.shipId === id).map(p => ({ ...p, low: p.stock <= p.minStock })),
      workOrders: db.workOrders.filter(w => w.shipId === id),
      costs,
      budget: db.budgets.find(x => x.shipId === id) || null,
      totalBiaya: total,
      leaves: db.leaves.filter(l => db.crews.find(c => c.id === l.crewId)?.shipId === id),
      activities: db.activities.filter(a => a.shipId === id)
    });
  }

  // KPI report
  if (seg.includes('reports') && seg.includes('kpi')) {
    const totalWO = db.workOrders.length;
    const doneOnTime = db.workOrders.filter(w => w.status === 'completed').length;
    const certNoNotif = db.crewCertificates.filter(c => expiryStatus(c.expiredAt).status === 'expired' && !db.notificationLogs.some(l => l.refId === c.id)).length;
    const docNoNotif = db.shipDocuments.filter(d => expiryStatus(d.expiredAt).status === 'expired' && !db.notificationLogs.some(l => l.refId === d.id)).length;
    return send(res, 200, {
      kepatuhanMaintenance: totalWO ? Math.round((doneOnTime / totalWO) * 100) : 100,
      targetMaintenance: 95,
      sertifikatExpiredTanpaNotif: certNoNotif,
      suratExpiredTanpaNotif: docNoNotif,
      targetNol: 0,
      totalWO,
      doneOnTime,
      totalNotif: db.notificationLogs.length
    });
  }

  // Cost reports
  if (seg.includes('reports') && seg.includes('costs')) {
    const s = q.get('shipId') || user.shipId || 'ship-1';
    const list = db.costs.filter(c => c.shipId === s);
    const total = list.reduce((a, c) => a + Number(c.amount || 0), 0);
    const bg = db.budgets.find(x => x.shipId === s);
    
    // Excel export
    if (q.get('format') === 'xls') {
      const rows = list.map(c => `<Row><Cell><Data ss:Type="String">${(c.date || '').slice(0, 10)}</Data></Cell><Cell><Data ss:Type="String">${c.kind}</Data></Cell><Cell><Data ss:Type="String">${String(c.note || '').replace(/[<>&]/g, '')}</Data></Cell><Cell><Data ss:Type="Number">${Number(c.amount || 0)}</Data></Cell></Row>`).join('');
      const xml = `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Biaya"><Table><Row><Cell><Data ss:Type="String">Tanggal</Data></Cell><Cell><Data ss:Type="String">Jenis</Data></Cell><Cell><Data ss:Type="String">Catatan</Data></Cell><Cell><Data ss:Type="String">Nominal</Data></Cell></Row>${rows}</Table></Worksheet></Workbook>`;
      res.setHeader('Content-Type', 'application/vnd.ms-excel');
      res.setHeader('Content-Disposition', `attachment; filename="biaya-${s}.xls"`);
      return res.status(200).send(xml);
    }
    
    // PDF export (simple)
    if (q.get('format') === 'pdf') {
      const lines = list.map(c => `${(c.date || '').slice(0, 10)} | ${c.kind} | ${String(c.note || '').slice(0, 40)} | Rp${Number(c.amount || 0)}`);
      const content = lines.join('\\n') + `\\n\\nTOTAL: Rp${total}`;
      res.setHeader('Content-Type', 'text/plain');
      res.setHeader('Content-Disposition', `attachment; filename="biaya-${s}.txt"`);
      return res.status(200).send(content);
    }
    
    return send(res, 200, { shipId: s, items: list, total, budget: bg?.amount || 0, sisa: (bg?.amount || 0) - total });
  }

  // Backup & restore
  if (seg.includes('backup')) {
    if (req.method === 'POST') {
      if (user.roleId !== 'super-admin') return send(res, 403, { error: 'Hanya super-admin' });
      const nd = req.body?.data || req.body;
      if (!nd || !Array.isArray(nd.ships)) return send(res, 400, { error: 'Invalid backup' });
      Object.keys(nd).forEach(k => { db[k] = nd[k]; });
      return send(res, 200, { ok: true, ships: db.ships.length });
    }
    if (user.roleId !== 'super-admin' && user.roleId !== 'fleet-manager') {
      return send(res, 403, { error: 'Hanya super-admin/fleet' });
    }
    return send(res, 200, { at: new Date().toISOString(), by: user.username, data: db });
  }

  // Scheduler run
  if (seg.includes('scheduler') && seg.includes('run')) {
    // Simplified scheduler for demo
    const logs = [];
    db.notificationLogs.unshift({ id: 'nl-' + Date.now(), targetType: 'demo', refId: 'demo', channel: 'mock', target: 'demo', status: 'terkirim-mock', at: new Date().toISOString() });
    return send(res, 200, { checked: true, sent: 1, logs });
  }

  // Generic CRUD untuk entities
  const MAPS = {
    ships: 'ships',
    equipments: 'equipments',
    schedules: 'schedules',
    'work-orders': 'workOrders',
    spareparts: 'spareparts',
    'sparepart-usages': 'sparepartUsages',
    costs: 'costs',
    budgets: 'budgets',
    crews: 'crews',
    'crew-certificates': 'crewCertificates',
    attendances: 'attendances',
    leaves: 'leaves',
    activities: 'activities',
    'ship-documents': 'shipDocuments',
    'notification-configs': 'notificationConfigs',
    'notification-logs': 'notificationLogs',
    'audit-logs': 'auditLogs',
    roles: 'roles',
    attachments: 'attachments',
    'work-order-checks': 'workOrderChecks',
    'work-order-approvals': 'workOrderApprovals',
    users: 'users'
  };

  // Auto-detect collection dari URL
  const collectionKey = Object.keys(MAPS).find(k => seg.includes(k));
  if (collectionKey) {
    const key = MAPS[collectionKey];
    const isReadOnly = ['notificationLogs', 'auditLogs'].includes(key);

    // GET collection
    if (req.method === 'GET' && seg.length === 2) {
      return send(res, 200, db[key] || []);
    }

    // POST create
    if (req.method === 'POST' && !isReadOnly) {
      if (!canWrite(user, key)) return send(res, 403, { error: 'Forbidden' });
      const item = { id: key.slice(0, 2) + '-' + Date.now().toString(36), ...req.body };
      db[key].push(item);
      return send(res, 201, item);
    }

    // PUT/DELETE by ID
    if (seg.length === 3) {
      const item = db[key].find(x => x.id === seg[2]);
      if (!item) return send(res, 404, { error: 'Not found' });

      if (req.method === 'PUT' && !isReadOnly) {
        if (!canWrite(user, key)) return send(res, 403, { error: 'Forbidden' });
        Object.assign(item, req.body);
        return send(res, 200, item);
      }

      if (req.method === 'DELETE' && !isReadOnly) {
        if (!canWrite(user, key)) return send(res, 403, { error: 'Forbidden' });
        db[key] = db[key].filter(x => x.id !== seg[2]);
        return send(res, 200, { ok: true });
      }
    }
  }

  // Fallback
  return send(res, 404, { error: 'Endpoint not found' });
}
